name: CI (light)

on:
  push:
  pull_request:

jobs:
  api-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install API deps
        if: hashFiles('api/requirements.txt') != ''
        run: pip install -r requirements.txt
      - name: API sanity
        run: python - << 'PY'
print("API folder present; deps installed (if any).")
PY

  flutter-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Pub get (best effort)
        run: |
          if [ -f "pubspec.yaml" ]; then
            flutter pub get || true
          fi
      - name: Analyze (best effort)
        run: |
          if [ -f "pubspec.yaml" ]; then
            flutter analyze || true
          else
            echo "No Flutter project at repo root; skipping."
          fi
